### ISSUE TITLE
one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!

### ISSUE THREAD

**Issue by yaskermezli** [snakemake/snakemake#1616] opened 2022-04-28 11:33 UTC
Hi, 
I'm using snakemake but in all my rules no one is excited correctly !!
I had this error : one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!
Here an example of a rule in my workflow:

rule sort_bed:
        input: expand("inp/bed/{bed}.bed", bed = BED_SMP)
        output:  expand("out/bedtools/sort/{bed}_sorted.bed", bed = BED_SMP)
        shell:"""
          bedtools sort -k1,1 -k2,2n -i {input} > {output} 
          """
Note that when I execute it in interactif way it works 

Any help please ?

Thank you.

**Comment by dariober** [comment] 2022-04-28 12:43
Hi- I would suggest you post this question to stackoverflow and close this issue since you may get more help there and most likely this is not a bug in snakemake. Before posting though, add more detail about your settings. E.g. show the output of running snakemake with and without `--dry-run` option. As it is, it is difficult if not impossible to tell what went wrong.

**Closed** 2022-04-28 12:55 UTC
Labels: bug
