### ISSUE TITLE
nested for loop in f-string

### ISSUE THREAD

**Issue by sneuensc** [snakemake/snakemake#2881] opened 2024-05-17 10:40 UTC
**Snakemake version**
Bug in latest versions. Tested versions 8.7.0 and 8.11.3.
Works in version 7.18.2

**Describe the bug**
I often use nested 'for' loops to create a list (outside of a rule). This works fine, but if the loop is placed WITHIN an f-string it does not work with the latest versions of snakemake. Before version 8 it was working.

**Logs**
$ snakemake -j1
SyntaxError in file Snakefile, line 6:
invalid syntax. Perhaps you forgot a comma? (Snakefile, line 6)

**Minimal example**
# works for both versions
a = [(x, y) for x in [1,2,3] for y in [3,1,4]]
print(f"works for both versions: {a}")

## works for older versions only
print(f"works only in old version: {[(x, y) for x in [1,2,3] for y in [3,1,4]]}")

**Comment by cmeesters** [comment] 2024-06-13 20:21
Snakemake states an error in your Snakefile. Please provide a minimal example to produce your error using the current version of Snakemake.

**Comment by Hocnonsense** [comment] 2024-06-25 12:44
Yes... This is indeed a bug that caused by f-string. 

In brief, python will split each 'word' in fstring such as `f"works only in old version: {`, `[`, `(`, `x`, `,`, `y`, `)`, `for`, `x`, `in` ...
however, the space between each word are missed. Snakemake read `smk` file using python parser, and this is difficult to keep it.

This bug will be fixed in the future, but it is also better to use f-string in a more gentle way :)

**Closed** 2024-07-04 08:30 UTC
Labels: bug
