### ISSUE TITLE
NotADirectoryError 

### ISSUE THREAD

**Issue by JackCaster** [snakemake/snakemake#391] opened 2020-05-13 03:16 UTC
**Snakemake version**
`5.17.0+19.gcaceb2ab` updated from master

**Describe the bug**
Cannot execute workflow after updating to master. Works fine with current pip version `5.17.0`

**Logs**
```
C:\Dev\test_snakemake>snakemake -n --cores 1
Traceback (most recent call last):
  File "c:\miniconda\envs\snakemake\lib\site-packages\snakemake\__init__.py", line 615, in snakemake
    success = workflow.execute(
  File "c:\miniconda\envs\snakemake\lib\site-packages\snakemake\workflow.py", line 614, in execute
    self.persistence = Persistence(
  File "c:\miniconda\envs\snakemake\lib\site-packages\snakemake\persistence.py", line 72, in __init__
    os.makedirs(d, exist_ok=True)
  File "c:\miniconda\envs\snakemake\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Dev\\test_snakemake\\.snakemake\\aux'
```

**Minimal example**
```
rule all:
    input:
        "test.txt"

rule touch:
    output:
        "test.txt"
    run:
        from pathlib import Path
        Path(str(output)).touch()
```

**Additional context**
OS: Windows 10

```
C:\Dev\test_snakemake>pip list
Package          Version
---------------- -------------------
appdirs          1.4.3
attrs            19.3.0
certifi          2020.4.5.1
chardet          3.0.4
ConfigArgParse   1.1
cycler           0.10.0
datrie           0.8.2
decorator        4.4.2
docutils         0.16
gitdb            4.0.2
GitPython        3.1.0
idna             2.9
ipython-genutils 0.2.0
jsonschema       3.2.0
jupyter-core     4.6.3
kiwisolver       1.0.1
matplotlib       3.1.3
mkl-fft          1.0.15
mkl-random       1.1.0
mkl-service      2.3.0
nbformat         5.0.5
numpy            1.18.1
pandas           1.0.3
pip              20.0.2
psutil           5.7.0
pyparsing        2.4.6
pyrsistent       0.16.0
python-dateutil  2.8.1
pytz             2019.3
pywin32          227
PyYAML           5.3.1
ratelimiter      1.2.0.post0
requests         2.23.0
setuptools       46.1.3.post20200330
sip              4.19.13
six              1.14.0
smmap            3.0.1
snakemake        5.17.0+19.gcaceb2ab
toposort         1.5
tornado          6.0.4
traitlets        4.3.3
urllib3          1.25.8
wheel            0.34.2
wincertstore     0.2
wrapt            1.12.1
```

**Comment by HappyPeng2x** [comment] 2020-05-23 07:06
I have the same issue with snakemake-minimal 5.18.1 from conda-forge on Windows 10.

According to MS documentation it is not possible to create a file or directory named aux on Windows.
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

It seems this is precisely what is happening in persistence.py from line 61:
```
        # place to store any auxilliary information needed during a run (e.g. source tarballs)
        self.aux_path = os.path.join(self.path, "aux")

        for d in (
            self._metadata_path,
            self.shadow_path,
            self.conda_env_archive_path,
            self.conda_env_path,
            self.container_img_path,
            self.aux_path,
        ):
            os.makedirs(d, exist_ok=True)
```

A change in the folder name should fix the issue, so it would be much appreciated.

**Comment by johanneskoester** [comment] 2020-05-25 09:36
Duplicate of #411. Let us go on there. Please raise your voice on the question I posted over there.

**Closed** 2020-05-25 12:24 UTC
Labels: bug
