### ISSUE TITLE
Errors in run directive are not raised and lead to obscure errors. 

### ISSUE THREAD

**Issue by SilasK** [snakemake/snakemake#1881] opened 2022-09-29 07:49 UTC
**Snakemake version**

7.14.2

python 3.10.6

**Describe the bug**

Errors in run directive are not raised and lead to obscure errors. 

Where does the logging statements go?
Where does the Exception go?

**Minimal example**

Snakefile:
```
rule run_with_error:
    output:
        touch("flag")
    run:
        print("before error")
        logger.info("logging")
        raise Exception("An error occured, but I don't see the erro rmessage")

```

**Logs**

```
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job               count    min threads    max threads
--------------  -------  -------------  -------------
run_with_error        1              1              1
total                 1              1              1

Select jobs to execute...

[Thu Sep 29 09:45:40 2022]
rule run_with_error:
    output: flag
    jobid: 0
    reason: Missing output files: flag
    resources: tmpdir=/tmp

before error
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-09-29T094540.574530.snakemake.log

```

**Additional context**

the snakemake log file. doesn't contain more info. even the print stement is not there.

**Comment by cgr71ii** [comment] 2022-09-29 14:00
Duplicate of https://github.com/snakemake/snakemake/issues/1698

**Closed** 2022-09-30 11:27 UTC
Labels: bug
