### ISSUE TITLE
workflow with piped output fails under versions 5.28 - 6.2

### ISSUE THREAD

**Issue by pdagosto** [snakemake/snakemake#975] opened 2021-04-28 18:44 UTC
**Snakemake version**
Note the Snakemake version for which you experience the bug.
Always make sure to try out the latest version before creating a new bug report.
5.28 - 6.2

**Describe the bug**
I have a workflow using piped output that worked under version 5.15 but fails under versions 5.28 - 6.2

**Logs**
If applicable, any terminal output to help explain your problem.
**(base) [pdagosto@rckgxf0013] $** snakemake_pipeline_error]$ snakemake --version
6.2.0
**(base) [pdagosto@rckgxf0013]$** snakemake_pipeline_error]$ snakemake -s test.make --cores 13
Building DAG of jobs...
WorkflowError in line 31 of /work/snakemake_pipeline_error/test.make:
An output file is marked as pipe, but consuming jobs are part of conflicting groups.

Note: the result is the same with any version equal to or later than 5.28

**(base) [pdagosto@rckgxf0013]$** snakemake_pipeline_error]$ snakemake --version
5.15.0
**(base) [pdagosto@rckgxf0013]$** snakemake_pipeline_error]$ snakemake -s test.make --cores 13
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 13
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	combineFiles
	2	qualityFilter
	2	trim
	2	unzip
	8
[Wed Apr 28 14:42:10 2021]

group job 95ac3254-fb7e-4109-aa87-467790da1111 (jobs in lexicogr. order):

    [Wed Apr 28 14:42:10 2021]
    rule combineFiles:
        input: qual_R1, qual_R2
        output: combined.fastq
        log: logs/combine.rpt
        jobid: 1

    [Wed Apr 28 14:42:10 2021]
    rule qualityFilter:
        input: trim_R2
        output: qual_R2 (pipe)
        log: logs/qual_R2.rpt
        jobid: 3
        wildcards: number=2

    [Wed Apr 28 14:42:10 2021]
    rule qualityFilter:
        input: trim_R1
        output: qual_R1 (pipe)
        log: logs/qual_R1.rpt
        jobid: 2
        wildcards: number=1

    [Wed Apr 28 14:42:10 2021]
    rule trim:
        input: unzip_R1
        output: trim_R1 (pipe)
        log: logs/trim_R1.rpt
        jobid: 4
        wildcards: number=1

    [Wed Apr 28 14:42:10 2021]
    rule trim:
        input: unzip_R2
        output: trim_R2 (pipe)
        log: logs/trim_R2.rpt
        jobid: 5
        wildcards: number=2

    [Wed Apr 28 14:42:10 2021]
    rule unzip:
        input: data/ValTest_DI/ValTest_DI_S1_L001_R2_001.fastq.gz
        output: unzip_R2 (pipe)
        log: logs/unzip_R2.rpt
        jobid: 7
        wildcards: number=2

    [Wed Apr 28 14:42:10 2021]
    rule unzip:
        input: data/ValTest_DI/ValTest_DI_S1_L001_R1_001.fastq.gz
        output: unzip_R1 (pipe)
        log: logs/unzip_R1.rpt
        jobid: 6
        wildcards: number=1

[Wed Apr 28 14:42:11 2021]
Finished job 6.
[Wed Apr 28 14:42:11 2021]
Finished job 7.
[Wed Apr 28 14:42:11 2021]
Finished job 5.
[Wed Apr 28 14:42:11 2021]
Finished job 4.
[Wed Apr 28 14:42:11 2021]
Finished job 3.
[Wed Apr 28 14:42:11 2021]
Finished job 2.
[Wed Apr 28 14:42:11 2021]
Finished job 1.
7 of 8 steps (88%) done

[Wed Apr 28 14:42:11 2021]
rule all:
    input: combined.fastq
    jobid: 0

done
[Wed Apr 28 14:42:11 2021]
Finished job 0.
8 of 8 steps (100%) done
Complete log: /work/snakemake_pipeline_error/.snakemake/log/2021-04-28T144210.733053.snakemake.log

**Minimal example**
Add a minimal example for reproducing the bug.
```
from glob import glob

logDir='logs'
readsPrefix= 'R'

rule all:
    input:
        'combined.fastq'
    shell:
        'echo "done"'

def getRawReadsFiles(wc):
    label = '{0}{1}'.format(readsPrefix, wc.number)
    reads=glob('data/ValTest_DI/ValTest_DI_S1_L001_R*.fastq.gz')
    files=[r for r in reads if re.search(label, r)]
    return files

rule unzip:
    input:
        getRawReadsFiles
    output:
        pipe('{0}_{1}{{number}}'.format('unzip', readsPrefix))
    log:
        '{0}/{1}_{2}{{number}}.rpt'.format(logDir, 'unzip', readsPrefix)
    shell:
        'gunzip -vc {input} 2>{log} > {output}'

def getTrimInput(wc):
    return 'unzip_{0}{1}'.format(readsPrefix, wc.number)

rule trim:
    input:
        file=getTrimInput
    output:
        pipe=pipe('{}_{}{{number}}'.format('trim', readsPrefix))
    log:
        '{0}/{1}_{2}{{number}}.rpt'.format(logDir, 'trim', readsPrefix)
    shell:
        'cat {input.file} | cutadapt --minimum-length 2 - 2>{log} > {output.pipe}'

def getQualInput(wc):
    return 'trim_{0}{1}'.format(readsPrefix, wc.number)

rule qualityFilter:
    input:
        file=getQualInput
    output:
        pipe=pipe('{}_{}{{number}}'.format('qual', readsPrefix))
    log:
        '{0}/{1}_{2}{{number}}.rpt'.format(logDir, 'qual', readsPrefix)
    shell:
        'cat {input.file} | fastq_quality_filter -q 20 -p 75 -Q 33 2>{log} > {output.pipe}'

rule combineFiles:
    input:
        expand('qual_{prefix}{num}', prefix=readsPrefix, num=[1,2])
    output:
        'combined.fastq'
    log:
        '{0}/{1}.rpt'.format(logDir, 'combine')
    shell:
        'cat {input} > {output}'

```
**Additional context**
CentOS 7
Python 3.7.10

**Comment by pdagosto** [comment] 2021-04-29 12:49
Added code formatting for the minimal example.

**Comment by TomHarrop** [comment] 2021-07-13 05:42
I'm having this issue too. After I upgraded to Snakemake 6.4.1, I get the error:

```
An output file is marked as pipe, but consuming jobs are part of conflicting groups.
```

After downgrading to 5.25.0 without any other changes to the workflow it runs fine.

I need pipes because I have lots of files and poor IO performance where I'm running my workflow, so I'm pinned to 5.25.0 for now.

**Comment by pdagosto** [comment] 2021-07-20 20:44
Any chance this will get assigned soon? I need to make use of features and bug fixes in later versions but cannot do so until there is a fix or work around for this issue.

**Comment by pdagosto** [comment] 2021-09-09 20:49
Just tried this with version 6.8. Everything is working now. Not sure what, if anything, changed.

**Comment by aryarm** [comment] 2021-09-10 19:24
Hi @pdagosto,
I've been trying to create a smaller, minimal example. Would you say this fits it?
```
rule all:
    input: "out.txt"

rule create1:
    output: pipe("text1_{num}")
    shell: "echo {wildcards.num} > {output}"

rule create2:
    input: rules.create1.output
    output: pipe("text2_{num}")
    shell: "cat {input} > {output}"

rule out:
    input: expand(rules.create2.output, num=range(2))
    output: "out.txt"
    shell: "cat {input} > {output}"
```
which gives us
```
$ snakemake -j
Building DAG of jobs...
WorkflowError in line 8 of Snakefile:
An output file is marked as pipe, but consuming jobs are part of conflicting groups.
```

**Comment by pdagosto** [comment] 2021-09-10 21:03
It seems to.

**Comment by aryarm** [comment] 2021-09-10 21:22
The more I think about it, the more I suspect this is intended behavior, then. From [the Snakemake docs for piped output](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#piped-output):

> However, the two jobs connected by a pipe may not exist in conflicting groups.

I'm guessing the reason for the error is that Snakemake is creating separate groups to handle each of the wildcards, but is then unable to merge them into a single group for the `out` rule (aka the aggregating step).

If we replace just the `pipe()` right before the aggregating step with a `temp()`, everything works because the groups no longer have to be merged:
```
rule all:
    input: "out.txt"

rule create1:
    output: pipe("text1_{num}")
    shell: "echo {wildcards.num} > {output}"

rule create2:
    input: rules.create1.output
    output: temp("text2_{num}") # replace this one pipe() with a temp()
    shell: "cat {input} > {output}"

rule out:
    input: expand(rules.create2.output, num=range(2))
    output: "out.txt"
    shell: "cat {input} > {output}"
```

## But there's still a bug!
But if my understanding about all of that is correct, then we should also just be able to solve the issue by forcing the rules to live inside the same group. So if I add `group` directives to each of the rules, it should work.
```
rule all:
    input: "out.txt"

rule create1:
    output: pipe("text1_{num}")
    group: 'pipes'
    shell: "echo {wildcards.num} > {output}"

rule create2:
    input: rules.create1.output
    output: pipe("text2_{num}")
    group: 'pipes'
    shell: "cat {input} > {output}"

rule out:
    input: expand(rules.create2.output, num=range(2))
    output: "out.txt"
    group: 'pipes'
    shell: "cat {input} > {output}"
```
And yet this doesn't work, either.
```
$ snakemake -j
Building DAG of jobs...
WorkflowError in line 9 of Snakefile:
An output file is marked as pipe, but consuming jobs are part of conflicting groups.
```

**Comment by pdagosto** [comment] 2021-09-10 21:56
Well if it's intended behavior it sure wasn't intended until version 5.28. Using temp is out of the question. So I guess we're going to stick with the versions that support this until I can figure out how to get around this, the snakemake guys come up with a fix or we decide to move on from snakemake.

**Comment by aryarm** [comment] 2021-09-10 21:59
I think we could fix it by fixing the bug. I'll try to take a look through the source code when I get a chance this weekend.

**Comment by aryarm** [comment] 2021-09-11 02:27
**Ok, new update:**
I tried [this minimal example](https://github.com/snakemake/snakemake/issues/975#issuecomment-917154545) on a bunch of different Snakemake versions. And I also tried the one with the group names explicitly added in. I've found that the issue was introduced somewhere between 5.26.1 and 5.27.4

**Comment by aryarm** [comment] 2021-09-11 08:34
Alright, I've spent a few more hours with this. I've learned a bit more about the issue but not really enough to fix it. I have a somewhat sketchy solution, though. tldr: see https://github.com/snakemake/snakemake/commit/3ffc1d876d231e29845be033dac74ac171a3ed2d

Basically, the issue that I'm seeing is that [the jobs in `self.needrun_jobs`](https://github.com/snakemake/snakemake/blob/55675e8b1c374dbe2e51c6b06ab5fb4617b73d2a/snakemake/dag.py#L1194) need to be in breadth-first-search order in order for the groups to be properly merged [here](https://github.com/snakemake/snakemake/blob/55675e8b1c374dbe2e51c6b06ab5fb4617b73d2a/snakemake/dag.py#L1267). But they usually aren't in bread-first-search order for some reason.
And the weird thing is that the order of the jobs in `self.needrun_jobs` seems to be dependent on some sort of timing. For example, when I add a `time.sleep()` [here](https://github.com/snakemake/snakemake/commit/3ffc1d876d231e29845be033dac74ac171a3ed2d), things seem to work. But when I comment it out, they don't anymore. 😕 I've repeated this experiment more than 50 times to confirm it isn't a fluke.
I'm guessing the amount of time required is somehow associated with the complexity of the DAG? I have a pretty simple DAG so that might be why it takes so little time.

There's [a commit that happened right around when things broke](https://github.com/snakemake/snakemake/commit/b563ed7a38ca68d8422a52af6a2148b5979e9e68#diff-7898111b777083eaffbb7e986fdf700073f388165a2f752a1477b374eff7ee52R879) that seems to do a lot of work with timing.
Next, I'm planning on taking a look at it to see if something there could explain the strange behavior I'm seeing.

**Comment by aryarm** [comment] 2021-09-11 20:18
Ok, new update: I'm fairly confident that the issue was introduced [here](https://github.com/snakemake/snakemake/commit/2e2c63a83f2511e5d79885036be1b9f2bf58f4db#diff-7898111b777083eaffbb7e986fdf700073f388165a2f752a1477b374eff7ee52L360):
```diff
    @property
    def needrun_jobs(self):
        """ Jobs that need to be executed. """
-        for job in filter(
-            self.needrun,
-            self.bfs(self.dependencies, *self.targetjobs, stop=self.noneedrun_finished),
-        ):
-            yield job
+        return filterfalse(self.finished, self._needrun)
```

`self.needrun_jobs` needs to return items in bread-first-search order for `self.handle_pipes()` to work properly. It seems to do this up until 2e2c63a8, where it instead gets its items from `self._needrun`. But `self._needrun` is **an ordered set** ❗

**Comment by aryarm** [comment] 2021-09-13 16:27
alright, I created a pull request to restore the old behavior

> Well if it's intended behavior it sure wasn't intended until version 5.28.

Yeah, I'm not sure. In any case, the pull request will get merged if it's intended behavior. And if it isn't, I can always revise the PR to work for [the other case](https://github.com/snakemake/snakemake/issues/975#issuecomment-917220287), in which the group names are specified explicitly.

**Comment by pdagosto** [comment] 2021-09-13 16:34
Sorry for the delay in responding - I don't seem to be getting e-mail notifications for new posts - have to check my settings. I really appreciate your help on this.  I hope the pull request will be accepted.

**Closed** 2021-09-24 13:48 UTC
Labels: bug
