### ISSUE TITLE
workflow.cores not defined when using --cluster option

### ISSUE THREAD

**Issue by andreott** [snakemake/snakemake#896] opened 2021-03-02 13:42 UTC
**Snakemake version**
Snakemake 6.0.0 (but also all previous)

**Describe the bug**
When using the `--cores` command line option, the value of `workflow.cores` is `None`

I use this value to determine the threads value for each rule (as it is also motivated in the docs). It might also be useful to make `--jobs` and `--cores` really two distinct options.

**Comment by johanneskoester** [comment] 2021-03-02 13:47
Thanks for reporting! I'll think about a good solution.

**Comment by johanneskoester** [comment] 2021-03-02 13:48
As a temporary workaround, you can use `--set-threads` to overwrite the threads for the problematic rule(s).

**Comment by andreott** [comment] 2021-03-02 21:10
Thanks! Currently I circumvent it by using some variable instead, which I set manually if workflow.cores is None. However now I just encountered the problem that in case of local rules the workflow.cores initially holds the local cores value (being then None again for the non local jobs). This is a problem (for my workaround) as my local rule is generating some config file where it will write the number of available threads for some job to be submitted. Is there some easy way to check within Snakemake if the "--cluster" option was used?

**Comment by jksull** [comment] 2021-03-03 10:36
Also wondering about a temporary workaround similar to above for my workflow being used by others, but would be easily executed either locally (workflow.cores not None and is equal to --cores), or on the cluster (where workflow.cores will be None), depending on the user and their available architecture.

**Comment by johanneskoester** [comment] 2021-06-10 13:57
The problem is that taking fractions does not really makes sense in a cluster setting right? A user would need to know what total number to specify then. E.g. in your situation above, when the user specifies 100, it would mean that a job with 50 threads will be submitted to the cluster, which does not make any sense on most systems.

One option I see is to make workflow.cores +inf and cap it with a new command line argument `--max-threads`.

**Comment by johanneskoester** [comment] 2021-06-10 13:58
This way, a user of your workflow could set `snakemake --max-threads 16` and all the jobs using fractions of workflow.cores would be scaled to 16.

**Comment by johanneskoester** [comment] 2021-06-10 14:00
The alternative, `snakemake --cluster qsub --cores N --jobs 100` would mean that the user will need to set N to a value such that it does not exceed the largest node on the cluster. That requires knowledge about all the rules in the workflow.

**Comment by johanneskoester** [comment] 2021-06-10 14:28
> The problem is that taking fractions does not really makes sense in a cluster setting right? A user would need to know what total number to specify then. E.g. in your situation above, when the user specifies 100, it would mean that a job with 50 threads will be submitted to the cluster, which does not make any sense on most systems.
> 
> One option I see is to make workflow.cores +inf and cap it with a new command line argument `--max-threads`.

I like this idea, because rules that use workflow.cores imply that they are infinitely scalable. Hence, whatever maximum is given they should be able to make use of it.

**Comment by johanneskoester** [comment] 2021-11-23 14:15
Fixed by PR #1049.

**Closed by johanneskoester** 2021-11-23 14:15 UTC
Labels: bug
