### ISSUE TITLE
Upcoming error for Python 3.8: time.clock deprecated in solvers.py

### ISSUE THREAD

**Issue by vsoch** [snakemake/snakemake#617] opened 2020-09-13 02:02 UTC
It looks like solvers.py uses "clock" from time, and running on 3.8.3 I get:
```
traceback (most recent call last):
  File "/home/vanessa/Desktop/Code/snakemake/snakemake/snakemake/__init__.py", line 643, in snakemake
    success = workflow.execute(
  File "/home/vanessa/Desktop/Code/snakemake/snakemake/snakemake/workflow.py", line 961, in execute
    success = scheduler.schedule()
  File "/home/vanessa/Desktop/Code/snakemake/snakemake/snakemake/scheduler.py", line 406, in schedule
    else self.job_selector_ilp(needrun)
  File "/home/vanessa/Desktop/Code/snakemake/snakemake/snakemake/scheduler.py", line 542, in job_selector_ilp
    import pulp
  File "/home/vanessa/Desktop/Code/snakemake/snakemake/env/lib/python3.8/site-packages/pulp/__init__.py", line 34, in <module>
    from .pulp import *
  File "/home/vanessa/Desktop/Code/snakemake/snakemake/env/lib/python3.8/site-packages/pulp/pulp.py", line 102, in <module>
    from .solvers import *
  File "/home/vanessa/Desktop/Code/snakemake/snakemake/env/lib/python3.8/site-packages/pulp/solvers.py", line 35, in <module>
    from time import clock
ImportError: cannot import name 'clock' from 'time' (unknown location)
unlocking
```
Another example report here: https://github.com/PyTables/PyTables/issues/744. I've opened an issue on the pulp board (linked below) so we can have guidance for fixes.

**Comment by dtrodrigues** [comment] 2020-09-14 02:29
This is resolved in the current version of pulp, but snakemake is pinning an older version: https://github.com/snakemake/snakemake/commit/c8a8fe264ace65f0e88595b495c0a67c94b2a9b9

**Comment by vsoch** [comment] 2020-09-14 02:32
Thank you @dtrodrigues. @johanneskoester is there a reason to pin to an earlier version?

**Comment by dtrodrigues** [comment] 2020-09-14 02:34
The changelog for 5.24.1of snakemake is 

https://github.com/snakemake/snakemake/commit/a7ac40c96d6e2af47102563d0478a2220e2a2ab7
> Depend on pulp < 2.0, which includes the default coin cbc solver for all platforms.

**Comment by mbargull** [comment] 2020-09-14 20:08
We updated the `conda-forge::pulp>=2.3` package (`2.3` just because we didn't package `>=2.0,<2.3`) to now depend on an external LP solver, so it is functioning again.
A future version of Snakemake can probably depend on `pulp>=2.0` now to avoid this Python 3.8 issue.

**Comment by vsoch** [comment] 2020-09-14 23:46
It looks like @johanneskoester explicitly constrained to an older version https://github.com/snakemake/snakemake/commit/c8a8fe264ace65f0e88595b495c0a67c94b2a9b9 so we should double check to see why, and if some newer version can satisfy both needs.

**Comment by mbargull** [comment] 2020-09-15 06:25
> It looks like @johanneskoester explicitly constrained to an older version

Indeed! He added that constraint because of the missing LP solver dependency and asked me to fix it :).
So, this is just me reporting back that that should be fixed now and Snakemake can be tested with a newer PuLP again ;).

**Comment by johanneskoester** [comment] 2020-09-15 10:53
Thank you guys!

**Comment by johanneskoester** [comment] 2020-09-15 11:12
Mhm, does not work yet: https://github.com/snakemake/snakemake/runs/1117214066#step:6:164

**Comment by johanneskoester** [comment] 2020-09-15 11:12
On windows, it fails to execute glpk @mbargull.

**Comment by johanneskoester** [comment] 2020-09-15 11:14
I have reverted to pulp <2.0 for now, until that is solved.

**Comment by johanneskoester** [comment] 2020-09-15 11:16
see PR #621 for the error.

**Comment by mbargull** [comment] 2020-09-15 11:42
Hm, it failed with https://github.com/snakemake/snakemake/runs/1117214066#step:6:135 :
```
C:\Users\RUNNER~1\AppData\Local\Temp\7120de09e16c4ff8a78d2b6274ec8a48-pulp.lp:5: missing constraint sense
```
I'll try to run the tests locally with GLPK on Linux and see if I can reproduce it and see what that `*-pulp.lp` contains.

**Comment by johanneskoester** [comment] 2020-09-15 14:26
Ok, finally fixed. Thanks everybody!

**Closed by johanneskoester** 2020-09-15 14:26 UTC
Labels: bug
