### ISSUE TITLE
7.3.8 claims output files have changed that haven't

### ISSUE THREAD

**Issue by pschloss** [snakemake/snakemake#1576] opened 2022-04-08 11:50 UTC
**Snakemake version**
7.3.8

**Describe the bug**
I'm running into an issue where when I dry-run (or run for real) a rule I get this message...

```
The code used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-code-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-code-changes)'.
```

When I look at the files that have changes, their time stamps are newer than the code used to generate them and the files have time stamps that are in the correct order. Some of these files take a long time to generate and I'd really rather not have to recreate them. 

Also, if the files have changed, then why wouldn't the DAG indicate that they need to be created? The files that supposedly have changes aren't getting updated the next time I run a rule.

As an example, `snakemake --list-code-changes` includes `data/references/silva.v4.align` and `data/references/silva.v4.tax`. Here's the rule...

```
rule silva:
  input:
    script="code/get_silva.sh"
  output:
    "data/references/silva.v4.align",
    "data/references/silva.v4.tax"
  resources:  
    cpus=8,
  shell:
    """
    {input.script} {resources.cpus}
    """
```

Here is the `ls -lth` output...

```
-rw-rw-r-- 1 pschloss schloss-lab 589K Apr  2 09:29 data/references/silva.v4.tax
-rw-rw-r-- 1 pschloss schloss-lab  53M Apr  2 09:29 data/references/silva.v4.align
-rwxrwxr-x 1 pschloss schloss-lab 1.4K Mar 29 09:52 code/get_silva.sh
```

googling the error message hasn't gotten me very far and I haven't been able to get very far. It sounds like this might be related to https://github.com/snakemake/snakemake/pull/1513

**Comment by SichongP** [comment] 2022-04-10 05:51
Do you experience this issue with earlier versions of snakemake?

**Comment by pschloss** [comment] 2022-04-11 16:58
Thanks @SichongP - I just went back and tried 7.2.1, 7.3.1, 7.3.3, 7.3.5, and 7.3.7 in addition to 7.3.8 with the same result.

**Comment by SichongP** [comment] 2022-04-11 20:16
Hmmm I wasan't able to reproduce this error. In your .snakemake/metadata folder there should be a file corresponding to this rule, which should have record of the shell command that was run, in addition to rule name, input, output, etc. Can you check that file and confirm that there indeed has been no changes?

**Comment by pschloss** [comment] 2022-10-11 08:52
Thanks - I wasn't aware of the metadata directory. It looks like the rule
was run again after the output files were created.

**Comment by pvandyken** [comment] 2022-12-22 15:53
Closing, as it looks like this is resolved, please reopen if there's more issues.

**Closed by pvandyken** 2022-12-22 15:53 UTC
Labels: bug
