### ISSUE TITLE
Breaking change: Snakemake 5.10 does not forward singularity-args for singularity anymore

### ISSUE THREAD

**Issue by chrarnold** [snakemake/snakemake#327] opened 2020-04-15 11:07 UTC
**Snakemake version**
Affects 5.10.0 onwards, but works until 5.9.1

**Describe the bug**
Our code is unchanged and worked for years, but suddenly I get this when executing an R script via the script directive: Even though I call snakemake with  --singularity-args "--bind /g/scb,/g/scb2,/scratch", I don't see these additional binds anymore in the subsequent singularity calls. it looks they are not passed through anymore? This is a breaking bug that deems all of our pipelines non-working. Please take a look.

EDIT: After more testing, I found that THE SAME pipeline and code works fine for snakemake 5.9.1, and only breaks from 5.10.0 onwards.

The command line call that is done is the following, note the missing additional binds: 

`singularity` exec --home bla  --bind bla2/TOOLS/miniconda3/lib/python3.7/site-packages:/mnt/snakemake bla3/singularity/bc12f9f5dd66bf5a09489dfa07c45231.simg bash -c `'Rscript --vanilla bla'`

**Comment by sschmeier** [comment] 2020-04-19 01:55
see here too: https://github.com/snakemake/snakemake/issues/193

**Comment by chrarnold** [comment] 2020-04-21 14:18
Please, this should be urgently addressed. A real limitation, 5.9.1 is the last version to use basically.

**Comment by andersgs** [comment] 2020-04-27 16:19
We are able to reproduce the same issue. It would be great to have this sorted...

In the meantime, we are considering packaging the Snakemake files with the tools in a single container, and run it all from within the container. A little more complicated, but it would be nice not to have to do that.

I have done some tracing, and as far as I can tell, the singularity-args param gets stored in a global context, but at some point, this global context is getting overwritten? If I get some time, I'll continue to dig to see if I can find anything more.

We do appreciate all the great work on Snakemake. Thank you!

**Comment by tseemann** [comment] 2020-04-27 21:38
@johanneskoester this regression bug that was introduced in 5.10 is still present in 5.16 (!)

**Comment by andersgs** [comment] 2020-04-29 22:40
I have **not** been able to replicate the bug on the latest version `5.16.0`. Seems to be working again.

**Comment by TomHarrop** [comment] 2020-04-30 22:17
I'm still having this issue in 5.16.0

**Comment by chrarnold** [comment] 2020-05-14 13:15
@johanneskoester Please comment upon, it seems to be still there and prevents any updates... Thanks!

**Comment by chrarnold** [comment] 2020-06-05 13:14
Ping... @johanneskoester . Is this fixed or not?

**Comment by tseemann** [comment] 2020-06-08 04:25
It seems to be working on snakemake-5.19.2

**Comment by chrarnold** [comment] 2020-06-29 12:16
It does still not work in 5.19.3... PLEASE, could someone take a look, we cannot use snakemake anymore in our group except versions until 5.9... It has been months now, a bit frustrating :(

**Comment by chrarnold** [comment] 2020-06-29 12:17
@johanneskoester Please take a look. This is a real pain this regression bug.

**Comment by johanneskoester** [comment] 2020-07-09 07:16
Thanks for letting me know. I apologize. With Snakemake, Bioconda, Rust-Bio and Rust-Htslib I get so many github notifications that I sometimes miss something urgent.

**Comment by johanneskoester** [comment] 2020-07-09 09:16
Fixed in Snakemake 5.20.1. A PR with some more tests for singularity would be much appreciated, in order to avoid such situations in the future :-).

**Closed by johanneskoester** 2020-07-09 09:16 UTC
Labels: bug

**Comment by andersgs** [comment] 2020-07-09 20:44
Thank you @johanneskoester! I'll try to work on that PR.
