### ISSUE TITLE
Container specification in rules needs fix

### ISSUE THREAD

**Issue by sschmeier** [snakemake/snakemake#625] opened 2020-09-16 07:53 UTC
**Snakemake version**
5.24.1

**Describe the bug**
The documentation mentions this in relation to use of containers [https://snakemake.readthedocs.io/en/v5.24.1/snakefiles/deployment.html#running-jobs-in-containers](https://snakemake.readthedocs.io/en/v5.24.1/snakefiles/deployment.html#running-jobs-in-containers):

```bash
rule NAME:
    input:
        "table.txt"
    output:
        "plots/myplot.pdf"
    container:
        "docker://joseespinosa/docker-r-ggplot2"
    script:
        "scripts/plot-stuff.R"
```

However, this throws an error as snakemake curnetly expects `container: "docker://joseespinosa/docker-r-ggplot2"` to be on the same line.

**Logs**

```bash
TypeError in line 13 of /scratch/bla/test/singularity/Snakefile:
container() missing 1 required positional argument: 'container_img'
  File "/scratch/bla/test/singularity/Snakefile", line 13, in <module>
```

**Comment by dcroote** [comment] 2020-10-23 07:03
Strangely, I was unable to reproduce your error with either v5.24.1 or the current latest version v5.26.1 using the Snakefile you provided. I ran it using the script and commands below on Ubuntu 20.04.1. What command are you using to run snakemake? Could you try the command below?

*scripts/plot-stuff.R*:
```R
pdf("plots/myplot.pdf")
y=rnorm(100,100,5)
plot(y)
dev.off()
```

*Run command* (`touch table.txt` is to make the create the rule input):
```bash
touch table.txt && snakemake --version && snakemake -j 1 -r --use-singularity
```

**v5.24.1 output**:
```bash
5.24.1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       NAME
        1

[Thu Oct 22 23:54:57 2020]
rule NAME:
    input: table.txt
    output: plots/myplot.pdf
    jobid: 0
    reason: Missing output files: plots/myplot.pdf

Activating singularity image /home/derek/sm-container-625/.snakemake/singularity/ca3a997dde3b7a79d95f44b4910bf056.simg
null device
          1
[Thu Oct 22 23:54:58 2020]
Finished job 0.
1 of 1 steps (100%) done
```

**v5.26.1 output**:
```bash
5.26.1
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       NAME
        1

[Thu Oct 22 23:55:48 2020]
rule NAME:
    input: table.txt
    output: plots/myplot.pdf
    jobid: 0
    reason: Missing output files: plots/myplot.pdf

Activating singularity image /home/derek/sm-container-625/.snakemake/singularity/ca3a997dde3b7a79d95f44b4910bf056.simg
null device
          1
[Thu Oct 22 23:55:49 2020]
Finished job 0.
1 of 1 steps (100%) done
```

**Comment by lssb** [comment] 2022-11-22 03:19
I have some ideas for this.

I met this Error today, and I found there was correct indent in Vim but error in VS code. Then I fixed indent in VS code and it works now.

**Closed** 2023-01-09 14:33 UTC
Labels: bug
