### ISSUE TITLE
JSONDecodeError while handling job success on LSF

### ISSUE THREAD

**Issue by omarelgarwany** [snakemake/snakemake#1342] opened 2022-01-20 14:21 UTC
**Snakemake version**
6.12.3

**Describe the bug**
This problem happens when running a snakemake pipeline on LSF. The pipeline exits immediately and it is not reported as a job failure. 

**Logs**
```
Traceback (most recent call last):
  File "/home/anaconda3/envs/gtex/lib/python3.7/site-packages/snakemake/__init__.py", line 783, in snakemake
    keepmetadata=keep_metadata,
  File "/home/anaconda3/envs/gtex/lib/python3.7/site-packages/snakemake/workflow.py", line 1073, in execute
    success = self.scheduler.schedule()
  File "/home/anaconda3/envs/gtex/lib/python3.7/site-packages/snakemake/scheduler.py", line 440, in schedule
    self._finish_jobs()
  File "/home/anaconda3/envs/gtex/lib/python3.7/site-packages/snakemake/scheduler.py", line 529, in _finish_jobs
    self.get_executor(job).handle_job_success(job)
  File "/home/anaconda3/envs/gtex/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 871, in handle_job_success
    job, upload_remote=False, handle_log=False, handle_touch=False
  File "/home/anaconda3/envs/gtex/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 272, in handle_job_success
    keep_metadata=self.keepmetadata,
  File "/home/anaconda3/envs/gtex/lib/python3.7/site-packages/snakemake/jobs.py", line 1033, in postprocess
    self, keep_metadata=keep_metadata
  File "/home/anaconda3/envs/gtex/lib/python3.7/site-packages/snakemake/persistence.py", line 239, in finished
    starttime = self._read_record(self._metadata_path, f).get(
  File "/home/anaconda3/envs/gtex/lib/python3.7/site-packages/snakemake/persistence.py", line 414, in _read_record_uncached
    return json.load(f)
  File "/home/anaconda3/envs/gtex/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/anaconda3/envs/gtex/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/anaconda3/envs/gtex/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/anaconda3/envs/gtex/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Minimal example**
I am running snakemake with these options:

`snakemake -j 1000 --latency-wait 90 -p --keep-going --config config1="config1" --cluster "rm logs/cluster/project_{rule}/{rule}.{wildcards}.out logs/cluster/project_{rule}/{rule}.{wildcards}.err ; mkdir -p logs/cluster/project_{rule}; bsub -R \"rusage[mem={resources.mem_mb}] select[mem>{resources.mem_mb}] span[hosts=1]\" -M {resources.mem_mb} -m \"modern_hardware\" -n {threads} -J \"project_{rule}.{wildcards}\" -G ${group} -o logs/cluster/project_{rule}/{rule}.{wildcards}.out -e logs/cluster/project_{rule}/{rule}.{wildcards}.err" -s project.Snakefile`

**Additional context**
I can't post the input files as it is on the LSF cluster

Any help or pointers will be very appreciated

**Comment by visze** [comment] 2022-01-24 10:03
Me an my colleagues observe the same issue on SLURM. But not all of us have them Completely reinstalling it helped for a while but after a while we run into that that again.

We were wondering if it's some package/library/python issue...

**Comment by visze** [comment] 2022-01-24 20:58
It is nearly the same error. differences maybe due to different snakemake versions. I use 6.13.1 and python 3.7

```
Full Traceback (most recent call last):
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/site-packages/snakemake/__init__.py", line 783, in snakemake
    keepmetadata=keep_metadata,
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/site-packages/snakemake/workflow.py", line 1073, in execute
    success = self.scheduler.schedule()
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/site-packages/snakemake/scheduler.py", line 440, in schedule
    self._finish_jobs()
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/site-packages/snakemake/scheduler.py", line 529, in _finish_jobs
    self.get_executor(job).handle_job_success(job)
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 875, in handle_job_success
    job, upload_remote=False, handle_log=False, handle_touch=False
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 272, in handle_job_success
    keep_metadata=self.keepmetadata,
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/site-packages/snakemake/jobs.py", line 1033, in postprocess
    self, keep_metadata=keep_metadata
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/site-packages/snakemake/persistence.py", line 239, in finished
    starttime = self._read_record(self._metadata_path, f).get(
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/site-packages/snakemake/persistence.py", line 414, in _read_record_uncached
    return json.load(f)
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/fast/users/schubacm_c/work/miniconda3/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3047 (char 3046)
```

**Comment by visze** [comment] 2022-01-31 11:41
I had a closer look. It reads a file form the folder `.snakemake/incomplete` and this one contains `{"external_jobid": null}74"}` Which is obviously not a correct json. It seems that the job ID from the cluster is not correctly retrieved

**Comment by visze** [comment] 2022-01-31 12:39
This line: https://github.com/snakemake/snakemake/blob/8c5c5e8261ae12fc40c3c293045dea6af7df0e01/snakemake/persistence.py#L393 Write several times the external_jobid to this file. First it writes something like `{"external_jobid": 2131274"}` (after submitting the job to the clsuter). Then it writes several times null to it. Basically because there is no job submission done. `{"external_jobid": null}`. But it seems that the old file is NOT overwritten. It just starts from the beginning and adds `{"external_jobid": null}` to it resulting in something like `{"external_jobid": null}74"}`

**Comment by funnell** [comment] 2022-02-09 20:37
I see the same thing happening for me (corrupted json in `.snakemake/incomplete`) on an LSF cluster with snakemake 6.7.0.

**Comment by gemygk** [comment] 2022-03-08 20:17
I get the same error on SLURM.

For me, it works if I remove the `.snakemake` directory. I had removed the `.snakemake` directory only once and all the restarts worked fine. As others mentioned earlier, it might be that some test runs corrupted the JSON file.

**Comment by mfansler** [comment] 2022-03-29 14:20
Removing `.snakemake` seems overkill to me. I was able to restore functionality after clearing out only the `.snakemake/metadata/` folder.

**Comment by visze** [comment] 2022-03-30 14:24
Yes the workaround works for me too. But it loses the information about incomplete files.

**Comment by pcm32** [comment] 2022-04-18 09:09
I also see this in the latest snakemake (7.3.x) + slurm, after a few runs of the same workflow.

**Comment by peter-yufan-zeng** [comment] 2022-04-23 01:06
having same issues with snakemake (7.3.8) on slurm.

**Comment by omarelgarwany** [comment] 2022-04-23 14:29
I got around this by disabling the --rerun-incomplete flag.

**Comment by nickp60** [comment] 2022-06-02 23:44
same issue here; having this sporadically on LSF.  deleting `.snakemake/metadata` fixes it

**Comment by holtgrewe** [comment] 2022-06-04 09:20
@nickp60 IMO what you observe is a symptom of snakemake trying to write to the same file from two concurrent processes. This occuring under cluster schedulers on clustered/network file systems is just as this is a prerequisite for running snakemake with sufficient parallelism to increase the probability of the problem occuring...

The resolution would be to use lock files with the `fasteners` package for example. This would require appropriate support for locks in the underlying file system. The only alternative that I can see would be a lock server running in the snakemake process and require allowing incoming network connections which may or may not be possible in the running environment.

@johanneskoester What is your opinion here? Is my root cause analysis likely correct or incorrect? Can we prevent a file from being opened twice? Would you agree to start with lock files and then trying to implement an opt-in network based lock system?

**Comment by nickp60** [comment] 2022-06-04 18:04
@holtgrewe Thanks for your input;  I don't know anything about snakemake's internals but that does seem plausible -- I tend to notice more often when I am developing workflows, stopping starting, etc.  I wonder if a simple check would be a good stopgap: something like
```python
# instead of 
return json.load(f)
# do
try:
    metadata_content = json.load(f)
except JSONDecodeError as e:
    logger.warning(f"Error reading metadata file {f}; this can be due to concurrent processes attempting to write to the same file. ")
    logger.warning(e)
    # delete offending file?
    metadata_content = dict()
return metadata_content
```

**Comment by johanneskoester** [comment] 2022-06-22 13:53
Hey folks, thanks for digging into this. So the idea was of course that those files are not at all written multiple times. Hence, there is no locking involved. I would rather like to find out why they are written multiple times instead of introducing a locking mechanism.

**Comment by johanneskoester** [comment] 2022-06-22 13:56
Do you have a clue whether the multiple writes maybe happen simultaneously on the main process of snakemake and job processes?

**Comment by johanneskoester** [comment] 2022-06-22 13:57
> @holtgrewe Thanks for your input; I don't know anything about snakemake's internals but that does seem plausible -- I tend to notice more often when I am developing workflows, stopping starting, etc. I wonder if a simple check would be a good stopgap: something like
> 
> ```python
> # instead of 
> return json.load(f)
> # do
> try:
>     metadata_content = json.load(f)
> except JSONDecodeError as e:
>     logger.warning(f"Error reading metadata file {f}; this can be due to concurrent processes attempting to write to the same file. ")
>     logger.warning(e)
>     # delete offending file?
>     metadata_content = dict()
> return metadata_content
> ```

Actually I like the idea to make this fallible (independent on solving the concurrent writing issue). Corrupt metadata should be treated as if there is no metadata available at all.

**Comment by nickp60** [comment] 2022-06-22 14:18
> Do you have a clue whether the multiple writes maybe happen simultaneously on the main process of snakemake and job processes?

I don't have a reproducible example but anecdotally it seems to be due to its interaction with the cluster scheduler.  I haven't (to my knowledge) run into this when executing rules locally. 

The snakefile itself is evaluated multiple times, right? Would it be related to the behavior that results in the phenomenon discussed [here](https://github.com/snakemake/snakemake/issues/1297)?

**Comment by johanneskoester** [comment] 2022-06-27 13:28
Ok, I just checked it in the code again. Persistence.finished() is called only from Job.postprocess(). That, in turn is only called when a Job finishes or fails. However, that happens on two levels, once inside of the cluster node, and then a second time in the main Snakemake process. The question is how that could possible introduce a race condition here. The main process is informed about the finalization of the job after the postprocess in the cluster node has been completed. Hence, I cannot really see how it would be possible here to have the two of them writing to that file at the same time.

I can see two scenarios:
1. Maybe you had some uncontrolled remaining Snakemake jobs from a previous execution running and they happened to write to those files while a new job for the same file was writing to it. This would be quite a coincidence though.
2. Maybe your NFS propagates the content somehow non-atomically, so that the propagation from the cluster node happens while the main node is writing its content for the metadata file?

Is 2. a realistic scenario?

In any case, I wonder whether it would make sense to implement a lock-free but also race-condition free mechanism: Persistence could first write to a temp file in the same dir, and then move it to the right place. The move should always be atomic (it just renames the file, also on NFS).

**Comment by johanneskoester** [comment] 2022-06-27 13:51
Regardless of the cause, above PR should hopefully fix those issues.

**Comment by nickp60** [comment] 2022-06-27 17:36
@johanneskoester Thank you so much!  I'll be pulling the code and will report back if I encounter this error again

**Comment by holtgrewe** [comment] 2022-06-28 06:23
Hi @johanneskoester. The issue is happening for us on the clustered file system spectrum scale (fka GPFS). I don't expect any of these issues with this file system as it implements no client caching AFAIK. Scenario \#1 is not happening for us either.

How is job completion in the main process detected? Also via some files? Sometimes GPFS access hangs on certain clients because of resource contention. Unless you have a true barrier that waits until the non-central/node `finished()` finished and the file is actually closed this may be a source of a race condition.

**Comment by holtgrewe** [comment] 2022-06-28 06:32
Does anyone have Lustre file system support and can ask about atomicity of POSIX `rename()` across multiple clients in Lustre?

**Comment by johanneskoester** [comment] 2022-06-28 08:58
@holtgrewe, could you also try with #1745?

**Comment by johanneskoester** [comment] 2022-06-28 09:00
@holtgrewe job completion detection depends on how the submission backend is configured. Either it waits for a flag file written by the job on the node to appear, or it queries the resource manager (via DRMAA, or via some custom profile).

**Comment by holtgrewe** [comment] 2022-07-14 05:53
Hi @johanneskoester, Dear all. IBM developers confirmed:

> GPFS is posix compliant. That has not changed over the years. If more than 1 client is trying to rename to the same destination, 1 client will win and have all its results in the file. This assumes no one will open the destination file and perform read/write to it.

I think we should abandon #1730, merge #1745 and close this ticket.

**Closed** 2022-07-19 10:05 UTC
Labels: bug

**Comment by johanneskoester** [comment] 2022-07-19 13:42
Thank you everybody for contributing to solving this!
