### ISSUE TITLE
crc32 import error

### ISSUE THREAD

**Issue by kdbinder** [snakemake/snakemake#534] opened 2020-08-04 17:51 UTC
**Snakemake version**
5.20.1, 5.20, 5.18...against the Google LifeSciences executor

**Describe the bug**
Python has issues importing the crc32 module from crc32c when using the packages deployed during the conda install

`WorkflowError:
The Python 3 packages 'google-cloud-sdk' and `crc32c` need to be installed to use GS remote() file functionality. cannot import name 'crc32' from 'crc32c' (/home/kbinder/miniconda3/envs/snakemake/lib/python3.8/site-packages/crc32c/__init__.py)`

**Logs**
Python 3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 02:25:52) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import crc32c
>>> from crc32c import crc32
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'crc32' from 'crc32c' (/home/kbinder/miniconda3/envs/snakemake/lib/python3.8/site-packages/crc32c/__init__.py)
>>> exit()

**Comment by johanneskoester** [comment] 2020-08-05 08:41
@vsoch I am not sure what suddenly caused this issue. It appeared first with commit 16f8e66e93754378205987ba8688c65436c1ea4d. But that commit did just change the docs. Hence, it must be something github actions or conda.

**Comment by johanneskoester** [comment] 2020-08-05 08:44
I am testing in this branch: https://github.com/snakemake/snakemake/tree/crc32c-dbg

It could be related to python 3.8 being rolled out in bioconda.

**Comment by vsoch** [comment] 2020-08-05 08:44
Thanks @kdbinder ! Could you please share enough context to reproduce the error?

**Comment by johanneskoester** [comment] 2020-08-05 08:46
We can already reproduce the error in the CI @vsoch. See here, where it first occured: https://github.com/snakemake/snakemake/runs/931015296

**Comment by johanneskoester** [comment] 2020-08-05 08:47
Could also be due to a new mamba release (rolling back to the previous one will be my next try).

**Comment by johanneskoester** [comment] 2020-08-05 08:48
Working now in this PR https://github.com/snakemake/snakemake/pull/538

**Comment by vsoch** [comment] 2020-08-20 14:11
hey @kdbinder this was fixed with #538, it should be the case that the import works correctly now. We switched from crc32c to google-crc32c.

**Closed by vsoch** 2020-08-20 14:11 UTC
Labels: bug
