### ISSUE TITLE
Python 3.8 not supported

### ISSUE THREAD

**Issue by brainstorm** [snakemake/snakemake#130] opened 2019-11-29 00:16 UTC
```
$ conda create -n umccrise python=3.8
(umccrise) $ conda install -c bioconda -c conda-forge snakemake
(...)
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - snakemake -> python[version='3.4.*|3.5.*|3.6.*|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8
```

**Comment by stanmart** [comment] 2020-02-13 10:19
It seems to me that the issue is that one of the dependencies [(datrie)](https://github.com/pytries/datrie) is stuck at 3.7. There is a PR to fix it, but it has not been merged for some time: https://github.com/pytries/datrie/pull/76

**Comment by mbhall88** [comment] 2020-02-26 13:32
This isn't necessarily a solution for conda but it is a fix for `pip3 install snakemake`.  (Although someone who uses conda may be able to tweak it to fix conda also?)

For python3.8 I found the following worked for me
```
pip3 install "git+https://github.com/ashwinvis/datrie.git@python3.8"
pip3 install snakemake
```
As @stanmart rightfully mentioned, this whole issue will be resolved once https://github.com/pytries/datrie/pull/76 is merged.

Also, see https://bitbucket.org/snakemake/snakemake/issues/934/installation-failed-in-python-37 for discussion on how to fix this issue for python3.7.

**Comment by stanmart** [comment] 2020-07-11 09:17
It seems to be solved now that datrie is updated. I think the issue can be closed.

**Closed** 2020-07-12 14:09 UTC
Labels: bug
