### ISSUE TITLE
The cleanup-metadata argument sometimes does not work

### ISSUE THREAD

**Issue by ning-y** [snakemake/snakemake#1497] opened 2022-03-18 03:53 UTC
**Snakemake version**

Versions 5.32.0 and 7.1.1. Others have reported versions 6.15.1 and 6.15.3.

**Describe the bug**

When Snakemake detects potentially incomplete files, it suggests to use `--cleanup-metadata` to mark those files as complete, if the user is certain that those files are not incomplete. In some cases, this does not work: after using `--cleanup-metadata`, Snakemake still raises an error about the same incomplete files.

This issue can be fixed by manually deleting the ~.snakemake/incomplete~ directory.

**Logs**

I first encountered this issue while using version 7.1.1.

```
(base) molecularonco:~/github/nccs-lcc $ snakemake --profile . -np --verbose
Building DAG of jobs...
Full Traceback (most recent call last):
  File "/home/molecularonco/miniconda3/lib/python3.8/site-packages/snakemake/__init__.py", line 714, in snakemake
    success = workflow.execute(
  File "/home/molecularonco/miniconda3/lib/python3.8/site-packages/snakemake/workflow.py", line 778, in execute
    dag.init()
  File "/home/molecularonco/miniconda3/lib/python3.8/site-packages/snakemake/dag.py", line 193, in init
    self.check_incomplete()
  File "/home/molecularonco/miniconda3/lib/python3.8/site-packages/snakemake/dag.py", line 337, in check_incomplete
    raise IncompleteFilesException(incomplete)
snakemake.exceptions.IncompleteFilesException: The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
InterVar
intermediates/our-study/intervar.tsv

IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
InterVar
intermediates/our-study/intervar.tsv
(base) molecularonco:~/github/nccs-lcc $ snakemake --cleanup-metadata InterVar intermediates/our-study/intervar.tsv --verbose
unlocking
removed all locks
(base) molecularonco:~/github/nccs-lcc $ snakemake --profile . -np --verbose
Building DAG of jobs...
Full Traceback (most recent call last):
  File "/home/molecularonco/miniconda3/lib/python3.8/site-packages/snakemake/__init__.py", line 714, in snakemake
    success = workflow.execute(
  File "/home/molecularonco/miniconda3/lib/python3.8/site-packages/snakemake/workflow.py", line 778, in execute
    dag.init()
  File "/home/molecularonco/miniconda3/lib/python3.8/site-packages/snakemake/dag.py", line 193, in init
    self.check_incomplete()
  File "/home/molecularonco/miniconda3/lib/python3.8/site-packages/snakemake/dag.py", line 337, in check_incomplete
    raise IncompleteFilesException(incomplete)
snakemake.exceptions.IncompleteFilesException: The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
InterVar
intermediates/our-study/intervar.tsv

IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
InterVar
intermediates/our-study/intervar.tsv
```

[Someone reported that using v5.32.0 fixed the issue](https://github.com/snakemake/snakemake/issues/828#issuecomment-767390845). So, I tried the above again using v5.32.0 installed via conda, but it failed to fix the issue.

**Minimal example**

This is a transient error, so I could not find a MWE for it.

**Additional context**

Reported in https://github.com/snakemake/snakemake/issues/828 also, but I believe that issue was prematurely closed.

**Comment by SichongP** [comment] 2022-03-24 17:30
I'm seeing the same issue with 6.10.0

**Comment by johanneskoester** [comment] 2022-04-01 09:38
Thanks for reporting! I think this might be caused by latency or concurrently writing jobs. I have for now implemented a warning in such cases and some hint what to do. If that does not solve your issue, feel free to reopen or re-report after above fix is merged.

**Closed** 2022-04-01 11:01 UTC
Labels: bug

**Comment by corneliusroemer** [comment] 2023-06-13 11:59
By passing `--ri` (`--rerun-incomplete`) by default to all my snakemake invocations I never have to worry about incomplete metadata.
