### ISSUE TITLE
subprocess.py Permission denied, shell command of first excecuted rule 

### ISSUE THREAD

**Issue by thomas-lacroix** [snakemake/snakemake#154] opened 2019-12-12 16:43 UTC
Hello,
After running snakemake on a Snakefile, I am seeing the following error:

		RuleException:
		PermissionError in line 50 of XXX/Snakefile:
		[Errno 13] Permission denied
		  File "XXX/Snakefile", line 50, in __rule_gb_to_faa
		  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
		  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
		  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run

The same snakemake command and Snakefile works for a collegue on a different computer.
The problem seems not to be related to the shell command of that first excecuted rule itself (this command works fine in the shell) but to the internal of snakemake (the error is the same for any command for that rule). --dryrun do not detect any error.
Can you help me with this error, I don't understand ?
Best wishes,
Thomas

**Comment by troycomi** [comment] 2019-12-16 17:43
Can you provide more context?  The rule code, the command attempting to be executed (run snakemake with -p), more of the log, etc?

My guess is when transferring from your colleague, you are trying to write to a directory they own or that doesn't exist and you can't write to a parent directory.  Without more information can't say for sure.

**Comment by thomas-lacroix** [comment] 2019-12-18 17:58
What is weird with this error is that the log points to the line of the snakefile where it executes the first command but the command being executed is irrelevant to the error. The same error occur if the command is a simple "touch", and in any case the command to be executed works fine if I run it in the command line. It is like Snakemake is written in python and when it reaches the part of the code that execute the command it needs the librairie subprocess.py and can not acess it. But when I run one of python script in the command line, I don't have this issue, this is a bit crazy...

**Comment by SichongP** [comment] 2019-12-19 18:16
Try running with `--verbose`?

**Comment by thomas-lacroix** [comment] 2019-12-27 13:40
Below is the log with --verbose. Any idea about what to test next to figure out why I am stuck ?

All required parameters are valid
Input arguments:
	Search mode:           hmm
	Genbank folder:        ../test_files/echantillon/
	software output: /home/userX/toolY/
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	4	gb_to_faa
	5
Resources before job selection: {'_cores': 1, '_nodes': 9223372036854775807}
Ready jobs (4):
	gb_to_faa
	gb_to_faa
	gb_to_faa
	gb_to_faa
Selected jobs (1):
	gb_to_faa
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}
rule gb_to_faa:
	input: /home/userX/toolY/tmp/genbank/genomeZ.gb
	output: /home/userX/toolY/tmp/genbank/genomeZ.csv
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 748, in run_wrapper
    version)
  File "/home/userX/montages_reseau/dirA/Snakefile", line 70, in __rule_gb_to_faa
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 63, in __new__
    close_fds=close_fds, **cls._process_args)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

Error in job gb_to_faa while creating output file /home/userX/toolY/tmp/genbank/genomeZ.csv.
Full Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 748, in run_wrapper
    version)
  File "/home/userX/montages_reseau/dirA/Snakefile", line 70, in __rule_gb_to_faa
  File "/usr/lib/python3/dist-packages/snakemake/shell.py", line 63, in __new__
    close_fds=close_fds, **cls._process_args)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 246, in _callback
    raise ex
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/snakemake/executors.py", line 762, in run_wrapper
    show_traceback=True))
snakemake.exceptions.RuleException: PermissionError in line 51 of /home/userX/montages_reseau/dirA/Snakefile:
[Errno 13] Permission denied
  File "/home/userX/montages_reseau/dirA/Snakefile", line 51, in __rule_gb_to_faa
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child

RuleException:
PermissionError in line 51 of /home/userX/montages_reseau/dirA/Snakefile:
[Errno 13] Permission denied
  File "/home/userX/montages_reseau/dirA/Snakefile", line 51, in __rule_gb_to_faa
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Releasing 1 _cores (now 1).
Releasing 1 _nodes (now 9223372036854775807).
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
unlocking
removing lock
removing lock
removed all locks

**Comment by SichongP** [comment] 2020-01-03 20:53
> It is like Snakemake is written in python and when it reaches the part of the code that execute the command it needs the librairie subprocess.py and can not acess it.

It doesn't seem like an issue with permission of subprocess.py module since you're getting an error thrown by this module.

This suggests that snakemake has parsed your shell code and tried to pass it to shell for execution (by calling subprocess module) but it was returned a permission denied error from the subprocess module.

This typically suggests that you don't have permission to do what you're trying to do with that rule. Do you have execute permission of the program you're trying to run? Do you have r/w permission to input/output files and directories?

**Comment by thomas-lacroix** [comment] 2020-01-05 17:48
Thanks for your message. Yes I have the permission to execute the command associated with the rule, when I run this command in the shell there is no error and it generates the output file.
Uninstalling / reinstalling python didn't resolve the problem, I will try upgrading from ubuntu 16 to 18 to see if it helps...

**Comment by thomas-lacroix** [comment] 2020-01-06 16:46
After a fresh install of ubuntu 18, the error seen in ubuntu 16 goes away...

**Comment by tbooth** [comment] 2020-01-13 11:38
Thanks for confirming the issue went away. I think we can reasonably assume this was a configuration issue on the Ubuntu box. If we could reproduce the exact situation it might be possible to make the error message clearer, but I think at this point there's unlikely to be progress on this issue, so I'm closing it. Please re-open if necessary.

**Closed by tbooth** 2020-01-13 11:38 UTC
